defaults: 
  docker: &docker
    - image: 'circleci/node:8-browsers'

version: 2
jobs:
  lint:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn lint
  test:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: 'yarn test:ci'
  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'dependency-cache-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: 'yarn build:ci'
workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test
      - build
